[build]
  publish = "web"
  command = "node scripts/generate-runtime-config.js && npm run build"


[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/public/landingpage.html"
  status = 200

