[build]
 [build]
  publish = "web"
  command = "node scripts/generate-runtime-config.js && cd web && npm install && npm run build"



[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/public/landingpage.html"
  status = 200

