-- Comprehensive Test Data for Student Card Management System
-- This script creates test data for 1000 students, multiple parents, staff, and admin users
-- Run this after schema.sql

-- ============================================
-- ADMIN USERS
-- ============================================
-- Note: Replace these hashes with actual bcrypt hashes generated by generate-hash.js
-- Password for all admins: admin123

INSERT INTO users (email, password_hash, role) VALUES
('admin@school.edu', '$2b$10$YOUR_ADMIN_HASH_HERE', 'admin'),
('principal@school.edu', '$2b$10$YOUR_ADMIN_HASH_HERE', 'admin'),
('registrar@school.edu', '$2b$10$YOUR_ADMIN_HASH_HERE', 'admin')
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- PARENT USERS (50 parents)
-- ============================================
-- Password for all parents: parent123
-- Note: Replace hashes with actual bcrypt hashes

DO $$
DECLARE
    i INTEGER;
    parent_hash TEXT := '$2b$10$YOUR_PARENT_HASH_HERE'; -- Replace with actual hash
    user_id_var INTEGER;
    parent_id_var INTEGER;
BEGIN
    FOR i IN 1..50 LOOP
        -- Create user account
        INSERT INTO users (email, password, role, status)
        VALUES ('parent' || i || '@example.com', parent_hash, 'parent', 'approved')
        ON CONFLICT (email) DO NOTHING
        RETURNING id INTO user_id_var;
        
        -- Get user_id if it already exists
        IF user_id_var IS NULL THEN
            SELECT id INTO user_id_var FROM users WHERE email = 'parent' || i || '@example.com';
        END IF;
        
        -- Create parent record
        INSERT INTO parents (user_id, name, email, phone)
        VALUES (
            user_id_var,
            CASE (i % 10)
                WHEN 0 THEN 'John ' || i || ' Smith'
                WHEN 1 THEN 'Mary ' || i || ' Johnson'
                WHEN 2 THEN 'David ' || i || ' Williams'
                WHEN 3 THEN 'Sarah ' || i || ' Brown'
                WHEN 4 THEN 'Michael ' || i || ' Jones'
                WHEN 5 THEN 'Emily ' || i || ' Garcia'
                WHEN 6 THEN 'James ' || i || ' Miller'
                WHEN 7 THEN 'Jessica ' || i || ' Davis'
                WHEN 8 THEN 'Robert ' || i || ' Rodriguez'
                WHEN 9 THEN 'Lisa ' || i || ' Martinez'
            END,
            'parent' || i || '@example.com',
            '+2547' || LPAD((100000000 + i)::TEXT, 9, '0')
        )
        ON CONFLICT (email) DO NOTHING
        RETURNING id INTO parent_id_var;
    END LOOP;
END $$;

-- ============================================
-- STAFF USERS (20 staff members)
-- ============================================
-- Password for all staff: staff123
-- Note: Replace hashes with actual bcrypt hashes

DO $$
DECLARE
    i INTEGER;
    staff_hash TEXT := '$2b$10$YOUR_STAFF_HASH_HERE'; -- Replace with actual hash
    user_id_var INTEGER;
    departments TEXT[] := ARRAY['Mathematics', 'Science', 'English', 'History', 'Physical Education', 'Arts', 'Music', 'Computer Science'];
    dept TEXT;
BEGIN
    FOR i IN 1..20 LOOP
        dept := departments[1 + (i % array_length(departments, 1))];
        
        -- Create user account
        INSERT INTO users (email, password_hash, role)
        VALUES ('staff' || LPAD(i::TEXT, 3, '0') || '@school.edu', staff_hash, 'staff')
        ON CONFLICT (email) DO NOTHING
        RETURNING id INTO user_id_var;
        
        -- Get user_id if it already exists
        IF user_id_var IS NULL THEN
            SELECT id INTO user_id_var FROM users WHERE email = 'staff' || LPAD(i::TEXT, 3, '0') || '@school.edu';
        END IF;
        
        -- Create staff record
        INSERT INTO staff (user_id, staff_no, name, email, phone, department, approved)
        VALUES (
            user_id_var,
            'STF' || LPAD(i::TEXT, 4, '0'),
            CASE (i % 10)
                WHEN 0 THEN 'Prof. Teacher ' || i
                WHEN 1 THEN 'Dr. Educator ' || i
                WHEN 2 THEN 'Mr. Instructor ' || i
                WHEN 3 THEN 'Mrs. Lecturer ' || i
                WHEN 4 THEN 'Ms. Tutor ' || i
                WHEN 5 THEN 'Prof. Mentor ' || i
                WHEN 6 THEN 'Dr. Guide ' || i
                WHEN 7 THEN 'Mr. Coach ' || i
                WHEN 8 THEN 'Mrs. Trainer ' || i
                WHEN 9 THEN 'Ms. Facilitator ' || i
            END,
            'staff' || LPAD(i::TEXT, 3, '0') || '@school.edu',
            '+2547' || LPAD((200000000 + i)::TEXT, 9, '0'),
            dept,
            CASE WHEN i <= 15 THEN true ELSE false END -- First 15 approved
        )
        ON CONFLICT (staff_no) DO NOTHING;
    END LOOP;
END $$;

-- ============================================
-- STUDENTS (1000 students)
-- ============================================
-- Students are distributed across grades 1-12
-- Each parent has 1-3 children

DO $$
DECLARE
    i INTEGER;
    parent_id_var INTEGER;
    parent_ids INTEGER[];
    grade_level INTEGER;
    class_section TEXT;
    sections TEXT[] := ARRAY['A', 'B', 'C', 'D'];
    student_name TEXT;
    gender TEXT;
    nemis_prefix TEXT;
    fee_balance DECIMAL;
    parent_index INTEGER;
    students_per_parent INTEGER;
    current_parent_index INTEGER := 1;
    students_for_current_parent INTEGER;
BEGIN
    -- Get all parent IDs
    SELECT ARRAY_AGG(id) INTO parent_ids FROM parents;
    
    -- Create 1000 students
    FOR i IN 1..1000 LOOP
        -- Determine grade (1-12)
        grade_level := 1 + ((i - 1) % 12);
        
        -- Determine class section
        class_section := sections[1 + ((i - 1) % array_length(sections, 1))];
        
        -- Assign parent (distribute students among parents)
        -- Each parent gets 1-3 students
        IF current_parent_index > array_length(parent_ids, 1) THEN
            current_parent_index := 1;
        END IF;
        
        parent_id_var := parent_ids[current_parent_index];
        
        -- Determine how many students this parent should have (1-3)
        students_for_current_parent := 1 + ((i - 1) % 3);
        
        -- Move to next parent after assigning students
        IF (i % students_for_current_parent = 0) OR (i = 1) THEN
            current_parent_index := current_parent_index + 1;
        END IF;
        
        -- Generate student name
        IF (i % 2 = 0) THEN
            -- Female names
            student_name := CASE ((i / 2) % 20)
                WHEN 0 THEN 'Emma ' || i
                WHEN 1 THEN 'Olivia ' || i
                WHEN 2 THEN 'Sophia ' || i
                WHEN 3 THEN 'Isabella ' || i
                WHEN 4 THEN 'Ava ' || i
                WHEN 5 THEN 'Mia ' || i
                WHEN 6 THEN 'Charlotte ' || i
                WHEN 7 THEN 'Amelia ' || i
                WHEN 8 THEN 'Harper ' || i
                WHEN 9 THEN 'Evelyn ' || i
                WHEN 10 THEN 'Abigail ' || i
                WHEN 11 THEN 'Emily ' || i
                WHEN 12 THEN 'Elizabeth ' || i
                WHEN 13 THEN 'Sofia ' || i
                WHEN 14 THEN 'Avery ' || i
                WHEN 15 THEN 'Ella ' || i
                WHEN 16 THEN 'Madison ' || i
                WHEN 17 THEN 'Scarlett ' || i
                WHEN 18 THEN 'Victoria ' || i
                WHEN 19 THEN 'Aria ' || i
            END;
            gender := 'Female';
        ELSE
            -- Male names
            student_name := CASE (((i + 1) / 2) % 20)
                WHEN 0 THEN 'James ' || i
                WHEN 1 THEN 'John ' || i
                WHEN 2 THEN 'Robert ' || i
                WHEN 3 THEN 'Michael ' || i
                WHEN 4 THEN 'William ' || i
                WHEN 5 THEN 'David ' || i
                WHEN 6 THEN 'Richard ' || i
                WHEN 7 THEN 'Joseph ' || i
                WHEN 8 THEN 'Thomas ' || i
                WHEN 9 THEN 'Charles ' || i
                WHEN 10 THEN 'Christopher ' || i
                WHEN 11 THEN 'Daniel ' || i
                WHEN 12 THEN 'Matthew ' || i
                WHEN 13 THEN 'Anthony ' || i
                WHEN 14 THEN 'Mark ' || i
                WHEN 15 THEN 'Donald ' || i
                WHEN 16 THEN 'Steven ' || i
                WHEN 17 THEN 'Paul ' || i
                WHEN 18 THEN 'Andrew ' || i
                WHEN 19 THEN 'Joshua ' || i
            END;
            gender := 'Male';
        END IF;
        
        -- Generate NEMIS number
        nemis_prefix := 'NEMIS-' || LPAD((1000000000 + i)::TEXT, 10, '0');
        
        -- Generate fee balance (0 to 50000, most students have some balance)
        fee_balance := CASE 
            WHEN (i % 10 = 0) THEN 0 -- 10% have no balance
            ELSE (RANDOM() * 50000)::DECIMAL(10,2) -- Others have varying balances
        END;
        
        -- Insert student
        INSERT INTO students (adm, name, nemis, class, fee_balance, parent_id)
        VALUES (
            'ST' || LPAD(i::TEXT, 5, '0'),
            student_name,
            nemis_prefix,
            'Grade ' || grade_level || ' - Section ' || class_section,
            fee_balance,
            parent_id_var
        )
        ON CONFLICT (adm) DO NOTHING;
        
        -- Progress indicator (every 100 students)
        IF i % 100 = 0 THEN
            RAISE NOTICE 'Inserted % students...', i;
        END IF;
    END LOOP;
    
    RAISE NOTICE 'Successfully inserted 1000 students!';
END $$;

-- ============================================
-- SUMMARY
-- ============================================
-- After running this script, you should have:
-- - 3 Admin users
-- - 50 Parent users (with accounts)
-- - 20 Staff members
-- - 1000 Students (distributed among parents)
--
-- Default Passwords (replace hashes in script):
-- - Admin: admin123
-- - Parent: parent123
-- - Staff: staff123
--
-- To generate proper password hashes, run:
-- node migrations/generate-hash.js

